2021-12-29 05:04:40,518 INFO    MainThread:5640 [wandb_setup.py:_flush():71] setting env: {}
2021-12-29 05:04:40,518 INFO    MainThread:5640 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-29 05:04:40,519 INFO    MainThread:5640 [wandb_init.py:_log_setup():371] Logging user logs to /content/drive/MyDrive/Colab Notebooks/stylegan2-pytorch/wandb/run-20211229_050440-2no6nk9b/logs/debug.log
2021-12-29 05:04:40,519 INFO    MainThread:5640 [wandb_init.py:_log_setup():372] Logging internal logs to /content/drive/MyDrive/Colab Notebooks/stylegan2-pytorch/wandb/run-20211229_050440-2no6nk9b/logs/debug-internal.log
2021-12-29 05:04:40,520 INFO    MainThread:5640 [wandb_init.py:init():404] calling init triggers
2021-12-29 05:04:40,520 INFO    MainThread:5640 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2021-12-29 05:04:40,520 INFO    MainThread:5640 [wandb_init.py:init():460] starting backend
2021-12-29 05:04:40,520 INFO    MainThread:5640 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-12-29 05:04:40,558 INFO    MainThread:5640 [backend.py:ensure_launched():216] starting backend process...
2021-12-29 05:04:40,596 INFO    MainThread:5640 [backend.py:ensure_launched():222] started backend process with pid: 5670
2021-12-29 05:04:40,599 INFO    MainThread:5640 [wandb_init.py:init():469] backend started and connected
2021-12-29 05:04:40,606 INFO    MainThread:5640 [wandb_init.py:init():533] updated telemetry
2021-12-29 05:04:40,751 INFO    MainThread:5640 [wandb_init.py:init():563] communicating current version
2021-12-29 05:04:41,592 INFO    MainThread:5640 [wandb_init.py:init():568] got version response 
2021-12-29 05:04:41,592 INFO    MainThread:5640 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2021-12-29 05:04:41,768 INFO    MainThread:5640 [wandb_init.py:init():606] starting run threads in backend
2021-12-29 05:04:44,132 INFO    MainThread:5640 [wandb_run.py:_console_start():1810] atexit reg
2021-12-29 05:04:44,134 INFO    MainThread:5640 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2021-12-29 05:04:44,135 INFO    MainThread:5640 [wandb_run.py:_redirect():1689] Redirecting console.
2021-12-29 05:04:44,136 INFO    MainThread:5640 [wandb_run.py:_redirect():1745] Redirects installed.
2021-12-29 05:04:44,136 INFO    MainThread:5640 [wandb_init.py:init():633] run started, returning control to user process
2021-12-29 05:04:45,513 INFO    MainThread:5640 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2021-12-29 05:04:45,517 INFO    MainThread:5640 [wandb_run.py:_restore():1752] restore
2021-12-29 05:04:47,660 INFO    MainThread:5640 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1304
  total_bytes: 1304
}

2021-12-29 05:04:47,843 INFO    MainThread:5640 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1304
  total_bytes: 1304
}

2021-12-29 05:04:48,834 INFO    MainThread:5640 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 1304
  total_bytes: 8870
}

2021-12-29 05:04:48,936 INFO    MainThread:5640 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1304
  total_bytes: 9534
}

2021-12-29 05:04:49,038 INFO    MainThread:5640 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9534
  total_bytes: 9534
}

2021-12-29 05:04:49,140 INFO    MainThread:5640 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9534
  total_bytes: 9534
}

2021-12-29 05:04:49,242 INFO    MainThread:5640 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9534
  total_bytes: 9534
}

2021-12-29 05:04:49,344 INFO    MainThread:5640 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9534
  total_bytes: 9534
}

2021-12-29 05:04:49,446 INFO    MainThread:5640 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9534
  total_bytes: 9534
}

2021-12-29 05:04:49,547 INFO    MainThread:5640 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9534
  total_bytes: 9534
}

2021-12-29 05:04:49,747 INFO    MainThread:5640 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9534
  total_bytes: 9534
}

2021-12-29 05:04:50,199 INFO    MainThread:5640 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9534
  total_bytes: 9534
}
local_info {
}

2021-12-29 05:04:51,655 INFO    MainThread:5640 [wandb_run.py:_append_files():2180] logging synced files
